
# All CCPP caps are defined here.
#
# This file is auto-generated using ccpp_prebuild.py
# at compile time, do not edit manually.
#
CAPS_F90 = 
	   ./physics/radsw_cap.F90 
	   ./physics/GFS_DCNV_generic_post_cap.F90 
	   ./physics/GFS_RRTMG_post_cap.F90 
	   ./physics/ozphys_cap.F90 
	   ./physics/GFS_suite_interstitial_rad_reset_cap.F90 
	   ./physics/GFS_MP_generic_pre_cap.F90 
	   ./physics/GFS_MP_generic_post_cap.F90 
	   ./physics/gscond_cap.F90 
	   ./physics/GFS_SCNV_generic_pre_cap.F90 
	   ./physics/dcyc2t3_post_cap.F90 
	   ./physics/cnvc90_cap.F90 
	   ./physics/gwdc_cap.F90 
	   ./physics/GFS_RRTMG_pre_cap.F90 
	   ./physics/GFS_zhao_carr_pre_cap.F90 
	   ./physics/GFS_PBL_generic_pre_cap.F90 
	   ./physics/radlw_cap.F90 
	   ./physics/GFS_suite_interstitial_1_cap.F90 
	   ./physics/gwdps_pre_cap.F90 
	   ./physics/GFS_suite_interstitial_3_cap.F90 
	   ./physics/GFS_suite_interstitial_2_cap.F90 
	   ./physics/dcyc2t3_pre_cap.F90 
	   ./physics/lsm_noah_pre_cap.F90 
	   ./physics/sasasshal_post_cap.F90 
	   ./physics/precpd_cap.F90 
	   ./physics/sfc_ex_coef_cap.F90 
	   ./physics/GFS_radsw_post_cap.F90 
	   ./physics/GFS_PBL_generic_post_cap.F90 
	   ./physics/sasasshal_cap.F90 
	   ./physics/GFS_surface_loop_control_part0_cap.F90 
	   ./physics/GFS_phys_time_vary_2_cap.F90 
	   ./physics/GFS_phys_time_vary_1_cap.F90 
	   ./physics/dcyc2t3_cap.F90 
	   ./physics/GFS_surface_loop_control_part1_cap.F90 
	   ./physics/sfc_sice_cap.F90 
	   ./physics/sfc_nst_post_cap.F90 
	   ./physics/GFS_surface_generic_post_cap.F90 
	   ./physics/sfc_nst_cap.F90 
	   ./physics/edmf_cap.F90 
	   ./physics/GFS_surface_loop_control_part2_cap.F90 
	   ./physics/GFS_radlw_pre_cap.F90 
	   ./physics/sfc_sice_pre_cap.F90 
	   ./physics/ozphys_pre_cap.F90 
	   ./physics/GFS_radsw_pre_cap.F90 
	   ./physics/lsm_noah_cap.F90 
	   ./physics/GFS_suite_interstitial_phys_reset_cap.F90 
	   ./physics/gwdps_cap.F90 
	   ./physics/sfc_nst_pre_cap.F90 
	   ./physics/GFS_SCNV_generic_post_cap.F90 
	   ./physics/GFS_rad_time_vary_cap.F90 
	   ./physics/lsm_noah_post_cap.F90 
	   ./physics/sasasdeep_cap.F90 
	   ./physics/GFS_initialize_scm_cap.F90 
	   ./physics/GFS_DCNV_generic_pre_cap.F90 
	   ./physics/gwdc_pre_cap.F90 
	   ./physics/sfc_diag_cap.F90 
	   ./physics/rayleigh_damp_cap.F90 
	   ./physics/GFS_radlw_post_cap.F90 
	   ./physics/sfc_sice_post_cap.F90 
	   ./physics/gwdc_post_cap.F90 
	   ./physics/GFS_suite_update_stateout_cap.F90 
	   ./physics/get_prs_fv3_cap.F90 
	   ./physics/GFS_surface_generic_pre_cap.F90 
	   ./physics/ozphys_post_cap.F90 
	   ./physics/GFS_calpreciptype_cap.F90 
	   ./physics/get_phi_fv3_cap.F90 
	   ./physics/gwdps_post_cap.F90