module micro_pumas_ccpp_dimensions_post
   use ccpp_kinds, only: kind_phys
! This will be replaced by subcolumn averaging when subcolumns are enabled

   public :: micro_pumas_ccpp_dimensions_post_run

contains
  !> \section arg_table_micro_pumas_ccpp_dimensions_post_run Argument Table
  !! \htmlinclude micro_pumas_ccpp_dimensions_post_run.html
  subroutine micro_pumas_ccpp_dimensions_post_run(ncol, micro_ncol, nlev, micro_nlev,                   &
                   nlevp1, micro_nlevp1, qcsinksum_rate1ord, micro_qcsinksum_rate1ord, airT_tend,       &
                   micro_airT_tend, airq_tend, micro_airq_tend,                                         &
                   cldliq_tend, micro_cldliq_tend, cldice_tend, micro_cldice_tend, numliq_tend,         &
                   micro_numliq_tend, numice_tend, micro_numice_tend, rainliq_tend, micro_rainliq_tend, &
                   snowice_tend, micro_snowice_tend, numrain_tend, micro_numrain_tend, numsnow_tend,    &
                   micro_numsnow_tend, graupice_tend, micro_graupice_tend, numgraup_tend,               &
                   micro_numgraup_tend, effc, micro_effc, effc_fn, micro_effc_fn, effi, micro_effi,     &
                   sadice, micro_sadice, sadsnow, micro_sadsnow, prect, micro_prect, preci, micro_preci,&
                   prec_evap, micro_prec_evap, am_evap_st, micro_am_evap_st, prec_prod, micro_prec_prod,&
                   cmeice, micro_cmeice, deffi, micro_deffi, pgamrad, micro_pgamrad, lamcrad,           &
                   micro_lamcrad, snowice_in_prec, micro_snowice_in_prec, scaled_diam_snow,             &
                   micro_scaled_diam_snow, graupice_in_prec, micro_graupice_in_prec,                    &
                   numgraup_vol_in_prec, micro_numgraup_vol_in_prec, scaled_diam_graup,                 &
                   micro_scaled_diam_graup, lflx, micro_lflx, iflx, micro_iflx, gflx, micro_gflx, rflx, &
                   micro_rflx, sflx, micro_sflx, rainliq_in_prec, micro_rainliq_in_prec, reff_rain,     &
                   micro_reff_rain, reff_snow, micro_reff_snow, reff_grau, micro_reff_grau,             &
                   numrain_vol_in_prec, micro_numrain_vol_in_prec, numsnow_vol_in_prec,                 &
                   micro_numsnow_vol_in_prec, refl, micro_refl, arefl, micro_arefl, areflz, micro_areflz,&
                   frefl, micro_frefl, csrfl, micro_csrfl, acsrfl, micro_acsrfl, fcsrfl, micro_fcsrfl,  &
                   refl10cm, micro_refl10cm, reflz10cm, micro_reflz10cm, rercld, micro_rercld, ncai,    &
                   micro_ncai, ncal, micro_ncal, rainliq, micro_rainliq, snowice, micro_snowice,        &
                   numrain_vol, micro_numrain_vol, numsnow_vol, micro_numsnow_vol, diam_rain,           &
                   micro_diam_rain, diam_snow, micro_diam_snow, graupice, micro_graupice, numgraup_vol, &
                   micro_numgraup_vol, diam_graup, micro_diam_graup, freq_graup, micro_freq_graup,      &
                   freq_snow, micro_freq_snow, freq_rain, micro_freq_rain, frac_ice, micro_frac_ice,    &
                   frac_cldliq_tend, micro_frac_cldliq_tend, rain_evap, micro_rain_evap,                &
                   errmsg, errcode)

    ! horizontal dimension
    integer, intent(in) :: ncol
    ! microphysics_horizontal_dimension
    integer, intent(in) :: micro_ncol
    ! vertical layer dimension
    integer, intent(in) :: nlev
    ! microphysics vertical layer dimension
    integer, intent(in) :: micro_nlev
    ! vertical interface dimension
    integer, intent(in) :: nlevp1
    ! microphysics vertical interface dimension
    integer, intent(in) :: micro_nlevp1

    !microphysics direct conversion rate of stratiform cloud water to precipitation (s-1)
    real(kind_phys), intent(in) :: micro_qcsinksum_rate1ord(:, :)
    !microphysics tendency of dry air enthalpy at constant pressure (J kg-1 s-1)
    real(kind_phys), intent(in) :: micro_airT_tend(:, :)
    !microphysics tendency of water vapor mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_airq_tend(:, :)
    !microphysics tendency of cloud liquid water mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_cldliq_tend(:, :)
    !microphysics tendency of cloud ice mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_cldice_tend(:, :)
    !microphysics tendency of mass number concentration of cloud liquid water wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(in) :: micro_numliq_tend(:, :)
    !microphysics tendency of mass number concentration of cloud ice wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(in) :: micro_numice_tend(:, :)
    !microphysics tendency of rain mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_rainliq_tend(:, :)
    !microphysics tendency of snow mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_snowice_tend(:, :)
    !microphysics tendency of mass number concentration of rain wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(in) :: micro_numrain_tend(:, :)
    !microphysics tendency of mass number concentration of snow wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(in) :: micro_numsnow_tend(:, :)
    !microphysics tendency of graupel mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_graupice_tend(:, :)
    !microphysics tendency of mass number concentration of graupel wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(in) :: micro_numgraup_tend(:, :)
    !microphysics effective radius of stratiform cloud liquid water particle (um)
    real(kind_phys), intent(in) :: micro_effc(:, :)
    !microphysics effective radius of stratiform cloud liquid water particle assuming droplet number concentration of 1e8 kg-1 (um)
    real(kind_phys), intent(in) :: micro_effc_fn(:, :)
    !microphysics effective radius of stratiform cloud ice particle (um)
    real(kind_phys), intent(in) :: micro_effi(:, :)
    !microphysics cloud ice surface area density (cm2 cm-3)
    real(kind_phys), intent(in) :: micro_sadice(:, :)
    !microphysics snow surface area density (cm2 cm-3)
    real(kind_phys), intent(in) :: micro_sadsnow(:, :)
    !microphysics LWE large scale precipitation rate at surface (m s-1)
    real(kind_phys), intent(in) :: micro_prect(:)
    !microphysics LWE large scale snowfall rate at surface (m s-1)
    real(kind_phys), intent(in) :: micro_preci(:)
    !microphysics precipitation evaporation rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_prec_evap(:, :)
    !microphysics precipitation evaporation area (fraction)
    real(kind_phys), intent(in) :: micro_am_evap_st(:, :)
    !microphysics precipitation production rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_prec_prod(:, :)
    !microphysics condensation minus evaporation rate of in-cloud ice wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_cmeice(:, :)
    !microphysics effective diameter of stratiform cloud ice particles for radiation (um)
    real(kind_phys), intent(in) :: micro_deffi(:, :)
    !microphysics cloud particle size distribution shape parameter (1)
    real(kind_phys), intent(in) :: micro_pgamrad(:, :)
    !microphysics cloud particle size distribution slope parameter (1)
    real(kind_phys), intent(in) :: micro_lamcrad(:, :)
    !microphysics snow mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(in) :: micro_snowice_in_prec(:, :)
    !microphysics snow scaled diameter (m)
    real(kind_phys), intent(in) :: micro_scaled_diam_snow(:, :)
    !microphysics graupel mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(in) :: micro_graupice_in_prec(:, :)
    !microphysics graupel number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(in) :: micro_numgraup_vol_in_prec(:, :)
    !microphysics graupel scaled diameter (m)
    real(kind_phys), intent(in) :: micro_scaled_diam_graup(:, :)
    !microphysics cloud liquid sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(in) :: micro_lflx(:, :)
    !microphysics cloud ice sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(in) :: micro_iflx(:, :)
    !microphysics graupel sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(in) :: micro_gflx(:, :)
    !microphysics rain sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(in) :: micro_rflx(:, :)
    !microphysics snow sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(in) :: micro_sflx(:, :)
    !microphysics rain mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(in) :: micro_rainliq_in_prec(:, :)
    !microphysics effective radius of stratiform rain particle (um)
    real(kind_phys), intent(in) :: micro_reff_rain(:, :)
    !microphysics effective radius of stratiform snow particle (um)
    real(kind_phys), intent(in) :: micro_reff_snow(:, :)
    !microphysics effective radius of stratiform graupel particle (um)
    real(kind_phys), intent(in) :: micro_reff_grau(:, :)
    !microphysics rain number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(in) :: micro_numrain_vol_in_prec(:, :)
    !microphysics snow number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(in) :: micro_numsnow_vol_in_prec(:, :)
    !microphysics analytic radar reflectivity at 94 GHz in precipitating fraction of gridcell (dBZ)
    real(kind_phys), intent(in) :: micro_refl(:, :)
    !microphysics analytic radar reflectivity at 94 GHz (dBZ)
    real(kind_phys), intent(in) :: micro_arefl(:, :)
    !microphysics analytic radar reflectivity z factor at 94 GHz (mm6 m-3)
    real(kind_phys), intent(in) :: micro_areflz(:, :)
    !microphysics fraction of gridcell with nonzero radar reflectivity (fraction)
    real(kind_phys), intent(in) :: micro_frefl(:, :)
    !microphysics analytic radar reflectivity at 94 GHz with CloudSat thresholds in precipitating fraction of gridcell (dBZ)
    real(kind_phys), intent(in) :: micro_csrfl(:, :)
    !microphysics analytic radar reflectivity at 94 GHz with CloudSat thresholds (dBZ)
    real(kind_phys), intent(in) :: micro_acsrfl(:, :)
    !microphysics fraction of gridcell with nonzero radar reflectivity with CloudSat thresholds (fraction)
    real(kind_phys), intent(in) :: micro_fcsrfl(:, :)
    !microphysics analytic radar reflectivity at 10 cm wavelength (dBZ)
    real(kind_phys), intent(in) :: micro_refl10cm(:, :)
    !microphysics analytic radar reflectivity z factor at 10 cm wavelength (mm6 m-3)
    real(kind_phys), intent(in) :: micro_reflz10cm(:, :)
    !microphysics effective radius of stratiform cloud liquid plus rain particles (m)
    real(kind_phys), intent(in) :: micro_rercld(:, :)
    !microphysics available ice nuclei number concentration of new state (m-3)
    real(kind_phys), intent(in) :: micro_ncai(:, :)
    !microphysics available cloud condensation nuclei number concentration of new state (m-3)
    real(kind_phys), intent(in) :: micro_ncal(:, :)
    !microphysics rain mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(in) :: micro_rainliq(:, :)
    !microphysics snow mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(in) :: micro_snowice(:, :)
    !microphysics rain number concentration of new state (m-3)
    real(kind_phys), intent(in) :: micro_numrain_vol(:, :)
    !microphysics snow number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(in) :: micro_numsnow_vol(:, :)
    !microphysics average diameter of stratiform rain particle (m)
    real(kind_phys), intent(in) :: micro_diam_rain(:, :)
    !microphysics average diameter of stratiform snow particle (m)
    real(kind_phys), intent(in) :: micro_diam_snow(:, :)
    !microphysics graupel mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(in) :: micro_graupice(:, :)
    !microphysics graupel number concentration of new state (m-3)
    real(kind_phys), intent(in) :: micro_numgraup_vol(:, :)
    !microphysics average diameter of stratiform graupel particle (m)
    real(kind_phys), intent(in) :: micro_diam_graup(:, :)
    !microphysics fraction of gridcell with graupel (fraction)
    real(kind_phys), intent(in) :: micro_freq_graup(:, :)
    !microphysics fraction of gridcell with snow (fraction)
    real(kind_phys), intent(in) :: micro_freq_snow(:, :)
    !microphysics fraction of gridcell with rain (fraction)
    real(kind_phys), intent(in) :: micro_freq_rain(:, :)
    !microphysics fraction of frozen water to total condensed water (fraction)
    real(kind_phys), intent(in) :: micro_frac_ice(:, :)
    !microphysics fraction of cloud liquid tendency applied to state (fraction)
    real(kind_phys), intent(in) :: micro_frac_cldliq_tend(:, :)
    !microphysics rain evaporation rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(in) :: micro_rain_evap(:, :)

    !direct conversion rate of stratiform cloud water to precipitation (s-1)
    real(kind_phys), intent(out) :: qcsinksum_rate1ord(:, :)
    !tendency of dry air enthalpy at constant pressure (J kg-1 s-1)
    real(kind_phys), intent(out) :: airT_tend(:, :)
    !tendency of water vapor mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: airq_tend(:, :)
    !tendency of cloud liquid water mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: cldliq_tend(:, :)
    !tendency of cloud ice mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: cldice_tend(:, :)
    !tendency of mass number concentration of cloud liquid water wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(out) :: numliq_tend(:, :)
    !tendency of mass number concentration of cloud ice wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(out) :: numice_tend(:, :)
    !tendency of rain mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: rainliq_tend(:, :)
    !tendency of snow mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: snowice_tend(:, :)
    !tendency of mass number concentration of rain wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(out) :: numrain_tend(:, :)
    !tendency of mass number concentration of snow wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(out) :: numsnow_tend(:, :)
    !tendency of graupel mixing ratio wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: graupice_tend(:, :)
    !tendency of mass number concentration of graupel wrt moist air and condensed water (kg-1 s-1)
    real(kind_phys), intent(out) :: numgraup_tend(:, :)
    !effective radius of stratiform cloud liquid water particle (um)
    real(kind_phys), intent(out) :: effc(:, :)
    !effective radius of stratiform cloud liquid water particle assuming droplet number concentration of 1e8 kg-1 (um)
    real(kind_phys), intent(out) :: effc_fn(:, :)
    !effective radius of stratiform cloud ice particle (um)
    real(kind_phys), intent(out) :: effi(:, :)
    !cloud ice surface area density (cm2 cm-3)
    real(kind_phys), intent(out) :: sadice(:, :)
    !snow surface area density (cm2 cm-3)
    real(kind_phys), intent(out) :: sadsnow(:, :)
    !LWE large scale precipitation rate at surface (m s-1)
    real(kind_phys), intent(out) :: prect(:)
    !LWE large scale snowfall rate at surface (m s-1)
    real(kind_phys), intent(out) :: preci(:)
    !precipitation evaporation rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: prec_evap(:, :)
    !precipitation evaporation area (fraction)
    real(kind_phys), intent(out) :: am_evap_st(:, :)
    !precipitation production rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: prec_prod(:, :)
    !condensation minus evaporation rate of in-cloud ice wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: cmeice(:, :)
    !effective diameter of stratiform cloud ice particles for radiation (um)
    real(kind_phys), intent(out) :: deffi(:, :)
    !cloud particle size distribution shape parameter (1)
    real(kind_phys), intent(out) :: pgamrad(:, :)
    !cloud particle size distribution slope parameter (1)
    real(kind_phys), intent(out) :: lamcrad(:, :)
    !snow mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(out) :: snowice_in_prec(:, :)
    !snow scaled diameter (m)
    real(kind_phys), intent(out) :: scaled_diam_snow(:, :)
    !graupel mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(out) :: graupice_in_prec(:, :)
    !graupel number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(out) :: numgraup_vol_in_prec(:, :)
    !graupel scaled diameter (m)
    real(kind_phys), intent(out) :: scaled_diam_graup(:, :)
    !cloud liquid sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(out) :: lflx(:, :)
    !cloud ice sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(out) :: iflx(:, :)
    !graupel sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(out) :: gflx(:, :)
    !rain sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(out) :: rflx(:, :)
    !snow sedimentation flux (kg m-2 s-1)
    real(kind_phys), intent(out) :: sflx(:, :)
    !rain mixing ratio wrt moist air and condensed water of new state in precipitating fraction of gridcell (kg kg-1)
    real(kind_phys), intent(out) :: rainliq_in_prec(:, :)
    !effective radius of stratiform rain particle (um)
    real(kind_phys), intent(out) :: reff_rain(:, :)
    !effective radius of stratiform snow particle (um)
    real(kind_phys), intent(out) :: reff_snow(:, :)
    !effective radius of stratiform graupel particle (um)
    real(kind_phys), intent(out) :: reff_grau(:, :)
    !rain number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(out) :: numrain_vol_in_prec(:, :)
    !snow number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(out) :: numsnow_vol_in_prec(:, :)
    !analytic radar reflectivity at 94 GHz in precipitating fraction of gridcell (dBZ)
    real(kind_phys), intent(out) :: refl(:, :)
    !analytic radar reflectivity at 94 GHz (dBZ)
    real(kind_phys), intent(out) :: arefl(:, :)
    !analytic radar reflectivity z factor at 94 GHz (mm6 m-3)
    real(kind_phys), intent(out) :: areflz(:, :)
    !fraction of gridcell with nonzero radar reflectivity (fraction)
    real(kind_phys), intent(out) :: frefl(:, :)
    !analytic radar reflectivity at 94 GHz with CloudSat thresholds in precipitating fraction of gridcell (dBZ)
    real(kind_phys), intent(out) :: csrfl(:, :)
    !analytic radar reflectivity at 94 GHz with CloudSat thresholds (dBZ)
    real(kind_phys), intent(out) :: acsrfl(:, :)
    !fraction of gridcell with nonzero radar reflectivity with CloudSat thresholds (fraction)
    real(kind_phys), intent(out) :: fcsrfl(:, :)
    !analytic radar reflectivity at 10 cm wavelength (dBZ)
    real(kind_phys), intent(out) :: refl10cm(:, :)
    !analytic radar reflectivity z factor at 10 cm wavelength (mm6 m-3)
    real(kind_phys), intent(out) :: reflz10cm(:, :)
    !effective radius of stratiform cloud liquid plus rain particles (m)
    real(kind_phys), intent(out) :: rercld(:, :)
    !available ice nuclei number concentration of new state (m-3)
    real(kind_phys), intent(out) :: ncai(:, :)
    !available cloud condensation nuclei number concentration of new state (m-3)
    real(kind_phys), intent(out) :: ncal(:, :)
    !rain mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(out) :: rainliq(:, :)
    !snow mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(out) :: snowice(:, :)
    !rain number concentration of new state (m-3)
    real(kind_phys), intent(out) :: numrain_vol(:, :)
    !snow number concentration of new state in precipitating fraction of gridcell (m-3)
    real(kind_phys), intent(out) :: numsnow_vol(:, :)
    !average diameter of stratiform rain particle (m)
    real(kind_phys), intent(out) :: diam_rain(:, :)
    !average diameter of stratiform snow particle (m)
    real(kind_phys), intent(out) :: diam_snow(:, :)
    !graupel mixing ratio wrt moist air and condensed water of new state (kg kg-1)
    real(kind_phys), intent(out) :: graupice(:, :)
    !graupel number concentration of new state (m-3)
    real(kind_phys), intent(out) :: numgraup_vol(:, :)
    !average diameter of stratiform graupel particle (m)
    real(kind_phys), intent(out) :: diam_graup(:, :)
    !fraction of gridcell with graupel (fraction)
    real(kind_phys), intent(out) :: freq_graup(:, :)
    !fraction of gridcell with snow (fraction)
    real(kind_phys), intent(out) :: freq_snow(:, :)
    !fraction of gridcell with rain (fraction)
    real(kind_phys), intent(out) :: freq_rain(:, :)
    !fraction of frozen water to total condensed water (fraction)
    real(kind_phys), intent(out) :: frac_ice(:, :)
    !fraction of cloud liquid tendency applied to state (fraction)
    real(kind_phys), intent(out) :: frac_cldliq_tend(:, :)
    !rain evaporation rate wrt moist air and condensed water (kg kg-1 s-1)
    real(kind_phys), intent(out) :: rain_evap(:, :)

    character(len=512), intent(out) :: errmsg  !PUMAS/CCPP error message (none)
    integer,            intent(out) :: errcode !CCPP error code (1)

    ! Set error variables
    errcode = 0
    errmsg = ''

    ilflx(:,:micro_nlevp1)              = micro_lflx(:ncol,:)
    iflx(:,:micro_nlevp1)               = micro_iflx(:ncol,:)
    gflx(:,:micro_nlevp1)               = micro_gflx(:ncol,:)
    rflx(:,:micro_nlevp1)               = micro_rflx(:ncol,:)
    sflx(:,:micro_nlevp1)               = micro_sflx(:ncol,:)
    pint(:,:micro_nlevp1)               = micro_pint(:ncol,:)
    qcsinksum_rate1ord(:,:micro_nlev)   = micro_qcsinksum_rate1ord(:ncol,:)
    airT_tend(:,:micro_nlev)            = micro_airT_tend(:ncol,:)
    airq_tend(:,:micro_nlev)            = micro_airq_tend(:ncol,:)
    cldliq_tend(:,:micro_nlev)          = micro_cldliq_tend(:ncol,:)
    cldice_tend(:,:micro_nlev)          = micro_cldice_tend(:ncol,:)
    numliq_tend(:,:micro_nlev)          = micro_numliq_tend(:ncol,:)
    numice_tend(:,:micro_nlev)          = micro_numice_tend(:ncol,:)
    rainliq_tend(:,:micro_nlev)         = micro_rainliq_tend(:ncol,:)
    snowice_tend(:,:micro_nlev)         = micro_snowice_tend(:ncol,:)
    numliq_tend(:,:micro_nlev)          = micro_numliq_tend(:ncol,:)
    numice_tend(:,:micro_nlev)          = micro_numice_tend(:ncol,:)
    numrain_tend(:,:micro_nlev)         = micro_numrain_tend(:ncol,:)
    numsnow_tend(:,:micro_nlev)         = micro_numsnow_tend(:ncol,:)
    graupice_tend(:,:micro_nlev)        = micro_graupice_tend(:ncol,:)
    numgraup_tend(:,:micro_nlev)        = micro_numgraup_tend(:ncol,:)
    effc(:,:micro_nlev)                 = micro_effc(:ncol,:)
    effc_fn(:,:micro_nlev)              = micro_effc_f(:ncol,:)
    effi(:,:micro_nlev)                 = micro_effi(:ncol,:)
    sadice(:,:micro_nlev)               = micro_sadice(:ncol,:)
    sadsnow(:,:micro_nlev)              = micro_sadsnow(:ncol,:)
    prect(:)                            = micro_prect(:ncol)
    preci(:)                            = micro_preci(:ncol)
    prec_evap(:,:micro_nlev)            = micro_prec_evap(:ncol,:)
    am_evap_st(:,:micro_nlev)           = micro_am_evap_st(:ncol,:)
    prec_prod(:,:micro_nlev)            = micro_prec_prod(:ncol,:)
    cmeice(:,:micro_nlev)               = micro_cmeice(:ncol,:)
    deffi(:,:micro_nlev)                = micro_deffi(:ncol,:)
    pgamrad(:,:micro_nlev)              = micro_pgamrad(:ncol,:)
    lamcrad(:,:micro_nlev)              = micro_lamcrad(:ncol,:)
    snowice_in_prec(:,:micro_nlev)      = micro_snowice_in_prec(:ncol,:)
    scaled_diam_snow(:,:micro_nlev)     = micro_scaled_diam_snow(:ncol,:)
    graupice_in_prec(:,:micro_nlev)     = micro_graupice_in_prec(:ncol,:)
    numgraup_vol_in_prec(:,:micro_nlev) = micro_numgraup_vol_in_prec(:ncol,:)
    scaled_diam_graup(:,:micro_nlev)    = micro_scaled_diam_graup(:ncol,:)
    lflx(:,:micro_nlev)                 = micro_lflx(:ncol,:)
    iflx(:,:micro_nlev)                 = micro_iflx(:ncol,:)
    gflx(:,:micro_nlev)                 = micro_gflx(:ncol,:)
    rlfx(:,:micro_nlev)                 = micro_rflx(:ncol,:)
    sflx(:,:micro_nlev)                 = micro_sflx(:ncol,:)
    rainliq_in_prec(:,:micro_nlev)      = micro_rainliq_in_prec(:ncol,:)
    reff_rain(:,:micro_nlev)            = micro_reff_rain(:ncol,:)
    reff_snow(:,:micro_nlev)            = micro_reff_snow(:ncol,:)
    reff_grau(:,:micro_nlev)            = micro_reff_grau(:ncol,:)
    numrain_vol_in_prec(:,:micro_nlev)  = micro_numrain_vol_in_prec(:ncol,:)
    numsnow_vol_in_prec(:,:micro_nlev)  = micro_numsnow_vol_in_prec(:ncol,:)
    refl(:,:micro_nlev)                 = micro_refl(:ncol,:)
    arefl(:,:micro_nlev)                = micro_arefl(:ncol,:)
    areflz(:,:micro_nlev)               = micro_areflz(:ncol,:)
    frefl(:,:micro_nlev)                = micro_frefl(:ncol,:)
    csrfl(:,:micro_nlev)                = micro_csrfl(:ncol,:)
    acsrfl(:,:micro_nlev)               = micro_acsrfl(:ncol,:)
    fcsrfl(:,:micro_nlev)               = micro_fcsrfl(:ncol,:)
    refl10cm(:,:micro_nlev)             = micro_refl10cm(:ncol,:)
    reflz10cm(:,:micro_nlev)            = micro_reflz10cm(:ncol,:)
    rercld(:,:micro_nlev)               = micro_rercld(:ncol,:)
    ncai(:,:micro_nlev)                 = micro_ncai(:ncol,:)
    ncal(:,:micro_nlev)                 = micro_ncal(:ncol,:)
    rainliq(:,:micro_nlev)              = micro_rainliq(:ncol,:)
    snowice(:,:micro_nlev)              = micro_snowice(:ncol,:)
    numrain_vol(:,:micro_nlev)          = micro_numrain_vol(:ncol,:)
    numsnow_vol(:,:micro_nlev)          = micro_numsnow_vol(:ncol,:)
    diam_rain(:,:micro_nlev)            = micro_diam_rain(:ncol,:)
    diam_snow(:,:micro_nlev)            = micro_diam_snow(:ncol,:)
    graupice(:,:micro_nlev)             = micro_graupice(:ncol,:)
    numgraup_vol(:,:micro_nlev)         = micro_numgraup_vol(:ncol,:)
    diam_graup(:,:micro_nlev)           = micro_diam_graup(:ncol,:)
    freq_graup(:,:micro_nlev)           = micro_freq_graup(:ncol,:)
    freq_snow(:,:micro_nlev)            = micro_freq_graup(:ncol,:)
    freq_rain(:,:micro_nlev)            = micro_freq_rain(:ncol,:)
    frac_ice(:,:micro_nlev)             = micro_frac_ice(:ncol,:)
    frac_cldliq_tend(:,:micro_nlev)     = micro_frac_cldliq_tend(:ncol,:)
    rain_evap(:,:micro_nlev)            = micro_rain_evap(:ncol,:)


    airT(ncol, nlev)
    micro_airT(micro_ncol, micro_nlev)

    micro_airT(:ncol,:) = airT(:,:micro_nlev)

  end subroutine micro_pumas_ccpp_dimensions_post_run
module micro_pumas_ccpp_dimensions_post
