name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - scidocs_hsd_aqua
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

    - name: Checkout current ccpp-physics code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install Doxygen + Graphviz + LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz perl texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra

    - name: Verify installations
      run: |
        which perl
        which bibtex
        doxygen --version

    - name: Build HSD docs
      run: |
        cd physics/docs
        doxygen ccpphsd_doxyfile

    - name: Checkout SCM V7
      uses: actions/checkout@v4
      with:
        repository: NCAR/ccpp-scm
        ref: v7.0.1
        path: v7_repo
        submodules: recursive

    - name: Generate metadata tables (SCM V7)
      run: |
        cd v7_repo

        export PYTHONPATH=$(pwd)/ccpp/framework/scripts:$(pwd)/ccpp/framework/scripts/parse_tools

        ./ccpp/framework/scripts/metadata2html.py -c ccpp/config/ccpp_prebuild_config.py

        mkdir -p ccpp/physics/physics/docs/html/V7
        mv ccpp/physics/physics/docs/*.html ccpp/physics/physics/docs/html/V7

    - name: Build V7 docs
      run: |
        cd ccpp/physics/physics/docs
        doxygen ccpp_doxyfile
        mv doc/html/* html/V7/

    - name: Checkout ufs-community SRWv3 branch
      uses: actions/checkout@v4
      with:
        repository: ufs-community/ccpp-physics
        ref: release/srw-v3
        path: srw_repo
        submodules: recursive

    - name: Build SRWv3 docs
      run: |
        cd srw_repo/physics/docs
        doxygen ccppsrw_doxyfile
        mkdir -p ../../../physics/docs/html/SRWv3
        mv doc/html/* ../../../physics/docs/html/SRWv3/

    - name: Checkout main branch again for landing page
      uses: actions/checkout@v4
      with:
        ref: scidocs_hsd_aqua
        path: main_repo

    - name: Build landing page
      run: |
        cd main_repo/physics/docs
        doxygen mainpage_doxyfile
        cp -r html/* $GITHUB_WORKSPACE/physics/docs/html/

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: physics/docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4.0.5
