name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - scidocs_hsd_aqua
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

    - name: Checkout current ccpp-physics code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Doxygen + Graphviz + LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz perl texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra

    - name: Verify installations
      run: |
        which perl
        which bibtex
        doxygen --version

    - name: Build HSD docs
      run: |
        cd physics/docs
        doxygen ccpphsd_doxyfile

    - name: Checkout V7 tag
      run: |
        git fetch --tags
        git checkout v7.0.0

    - name: Build V7 docs
      run: |
        cd physics/docs
        doxygen ccpp_doxyfile
        mkdir -p html/V7
        mv doc/html/* html/V7/

    - name: Create landing page
      run: |
        cat << 'EOF' > physics/docs/html/index.html
        <!DOCTYPE html>
        <html>
        <head>
            <title>CCPP Physics Scientific Documentation</title>
            <link rel="stylesheet" href="_doxygen/doxygen-awesome.css">
            <link rel="stylesheet" href="_doxygen/doxygen-awesome-sidebar-only.css">
            <link rel="stylesheet" href="_doxygen/doxygen-awesome-sidebar-only-darkmode-toggle.css">
            <link rel="stylesheet" href="_doxygen/doxygen-awesome-ccpp.css">
            <style>
            </style>
        </head>
        <body>
            <div class="container">
                <h1>CCPP Physics Scientific Documentation</h1>

                <p>The Common Community Physics Package (CCPP) provides scientific documentation for the physics suites and parameterizations used across a variety of atmospheric modeling applications. The documentation describes the scientific basis, configuration options, and implementation details for the parameterizations included in the CCPP physics suites for different modeling systems and use cases.</p>

                <a href="./V7/">CCPP Physics V7 Scientific Documentation</a>

                <a href="./HSD/">CCPP Physics Hierarchical System Development (HSD) Scientific Documentation</a>

            </div>
        </body>
        </html>
        EOF

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: physics/docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4.0.5
