name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - scidocs_hsd_aqua
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

    - name: Install Doxygen + Graphviz + LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz perl texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra

    - name: Verify installations
      run: |
        which perl
        which bibtex
        doxygen --version

    - name: Checkout CCPP SCM v7
      uses: actions/checkout@v4
      with:
        repository: NCAR/ccpp-scm
        ref: v7.0.0
        path: scm_repo
        submodules: recursive 

    - name: Generate metadata tables v7 branch
      run: |
        cd scm_repo
        mkdir -p $GITHUB_WORKSPACE/physics/docs/html/V7
        export PYTHONPATH=$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts:$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts/parse_tools
        ./ccpp/framework/scripts/metadata2html.py -c ccpp/config/ccpp_prebuild_config.py -o $GITHUB_WORKSPACE/physics/docs/html/V7

    - name: Build V7 docs
      run: |
        cd scm_repo/ccpp/physics/physics/docs
        doxygen ccpp_doxyfile
        mv doc/html/* $GITHUB_WORKSPACE/physics/docs/html/V7

    - name: Switch physics submodule to main branch
      run: |
        cd scm_repo/ccpp/physics
        git fetch origin
        git checkout main
        git pull origin main

    - name: Generate metadata tables main branch
      run: |
        cd scm_repo
        mkdir -p $GITHUB_WORKSPACE/physics/docs/html/HSD
        export PYTHONPATH=$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts:$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts/parse_tools
   #     ./ccpp/framework/scripts/metadata2html.py -c ccpp/physics/physics/docs/pdftxt/HSD/ccpp_prebuild_config.py -o $GITHUB_WORKSPACE/physics/docs/html/HSD

    - name: Build HSD docs
      run: |
        cd scm_repo/ccpp/physics/physics/docs
        doxygen ccpphsd_doxyfile
        mv doc/html/* $GITHUB_WORKSPACE/physics/docs/html/HSD

    - name: Switch physics submodule to SRWv3 (ufs-community)
      run: |
        cd scm_repo/ccpp/physics
        git remote set-url origin https://github.com/ufs-community/ccpp-physics.git
        git fetch origin release/srw-v3
        git checkout -B release/srw-v3 FETCH_HEAD

    - name: Generate metadata tables SRWv3 branch
      run: |
        cd scm_repo
        mkdir -p $GITHUB_WORKSPACE/physics/docs/html/SRWv3
        export PYTHONPATH=$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts:$GITHUB_WORKSPACE/scm_repo/ccpp/framework/scripts/parse_tools
    #    ./ccpp/framework/scripts/metadata2html.py -c ccpp/config/ccpp_prebuild_config.py -o $GITHUB_WORKSPACE/physics/docs/html/SRWv3

    - name: Build SRWv3 docs
      run: |
        cd scm_repo/ccpp/physics/physics/docs
        doxygen ccppsrw_doxyfile
        mv doc/html/* $GITHUB_WORKSPACE/physics/docs/html/SRWv3

    - name: Switch to submodule main (ncar)
      run: |
        cd scm_repo/ccpp/physics
        git remote set-url origin https://github.com/hertneky/ccpp-physics.git
        git fetch origin scidocs_hsd_aqua
        git checkout scidocs_hsd_aqua

    - name: Build landing page
      run: |
        cd scm_repo/ccpp/physics/physics/docs
        doxygen mainpage_doxyfile
        mv html/* $GITHUB_WORKSPACE/physics/docs/html

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: physics/docs/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4.0.5
